### ISSUE TITLE
Model canvas drawing solution

### ISSUE THREAD

**Issue by BaBrixx** [ECDAR-AAU-SW-P5/Ecdar-GUI-Web#8]
To make sure that the solution for drawing the model canvas is able to efficiently draw as much nodes as possible, a couple of tests has to be performed.

The solutions that should be tested are the following:
- [x] #10
- [x] #11
- [x] #12

**Comment by NybyDK** [comment]
**"Draw Prototype" Performance Measurements**
- How many circles with text that are connected to exactly 2 other random circles can we add and still run smoothly?
 - Individual circles must be draggable and connections move with.
 - The whole "canvas" must be pannable.
 - The whole "canvas" must be zoomable.

Sizes should be irrelevant?
"Draw" any duplicate connections between circles anyway, since they are random and might be duplicate but should be fair to the test?
